### ISSUE TITLE
Scripts para revisar

### ISSUE THREAD

**Issue by JavierFM-210971** [JavierFM-210971/testsim#1]
No sé si tienes disponibles los archivos que contienen los scripts.
Ya me dices. Un Saludo.

Javier

**Comment by tdido** [comment]
Buenas, Javier.

Para que pueda ver los scripts hace falta que hagas un commit y lo subas al repo. Básicamente, desde el directorio "testsim", tenés que ejecutar estos comandos:

```
git add .
git commit -m "Add script versions to review."
git push
```

**Comment by JavierFM-210971** [comment]
Hola Tomás,
Me dice que todo está actualizado ("Everything up-to date")

**Comment by tdido** [comment]
Tenés razón, Javier. Me olvidé de que vos ya habías subido los cambios durante la clase.

Está todo perfecto, funciona correctamente. El único comentario menor es que no tiene mucho sentido exportar el ambiente de conda cada vez que se ejecutan los script, con lo cual la idea era eso hacerlo manualmente una única vez.

Cierro igualmente la incidencia porque el ejercicio está completo.
